name: Deploy Function

on:
  push:
    branches:
      - create-initial-structure
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: tdvwkylywuowwkeizjed

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy test-workflow --project-ref $PROJECT_ID
        working-directory: ./backend/
