name: Deploy Function & Migration

on:
  workflow_run:
    workflows:
      - test-backend
    types:
      - completed

jobs:
  deploy-function:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: tdvwkylywuowwkeizjed

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy test-workflow --project-ref $PROJECT_ID
        working-directory: ./backend/
  deploy-migration:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: tdvwkylywuowwkeizjed

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $PROJECT_ID --password $SUPABASE_DB_PASSWORD
        working-directory: ./backend/
      - run: supabase db push
        working-directory: ./backend/
