name: test-backend

on:
  push:
    branches:
      - "**"

jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase start --exclude realtime,storage-api,imgproxy,kong,inbucket,postgres-meta,studio,edge-runtime,logflare,vector
        working-directory: ./backend/
      - run: supabase test db
        working-directory: ./backend/
